### ISSUE TITLE
非自动播放gif获取不到数据

### ISSUE THREAD

**Issue by tianpanpan66** [likaia/gif-parser-web#2]
![d6cf78da7ee9f06f2949e9608d4997b5](https://user-images.githubusercontent.com/28037665/219620756-dd5d3bc7-3733-4b30-a045-f09b2e589d0b.gif)
<img width="209" alt="image" src="https://user-images.githubusercontent.com/28037665/219620954-f98793dd-38b3-479c-8210-93ebaf40d72c.png">

**Comment by likaia** [comment]
无解 😂 不支持解析
