### ISSUE TITLE
图片跨域

### ISSUE THREAD

**Issue by cccnobody** [likaia/gif-parser-web#3]
能不能给 fetch 新增一个可选参数 { mode: 'no-cors' }，否则调用外部图片会跨域。

**Comment by likaia** [comment]
> 能不能给 fetch 新增一个可选参数 { mode: 'no-cors' }，否则调用外部图片会跨域。

你可以在自己的项目里去写fetch来获取图片资源，拿到文件流之后，调用插件的`getInfo`方法即可
